config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('courses/', include('courses.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

courses/urls.py
from django.urls import path

from . import views

app_name = 'courses'

urlpatterns = [
    path('create', views.CreateCourseView.as_view(), name='create-course'),
    path('new-subject/', views.CreateSubjectView.as_view(), name='create-subject'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login', views.login_user_view, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('register', views.registration_view, name='registration'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>LMS - {% block title %}{% endblock %}</title>
    {% block styles %}
        <link rel="stylesheet" href="{% static 'styles/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    {% endblock %}
    {% block scripts %}
        <script src="{% static 'scripts/bootstrap.min.js' %}" defer async></script>
    {% endblock %}

</head>
<body>
{% include 'navbar.html' %}

<div class="container-lg mt-3">
    <div class="row">
        <div class="col-12 col-md-9">
            {% block container %}

            {% endblock %}
        </div>
        <div class="col-12 col-md-3">
            {% block aside %}
                
            {% endblock %}
        </div>
    </div>
</div>



</body>
</html>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-lg">
    <a class="navbar-brand" href="{% url 'home:home' %}">
        <img src="{% static 'images/Logo.svg' %}" class="logo" alt="logo">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>

          {% if user.is_authenticated %}
              <a class="nav-link" href="">Profile: {{ user }}</a>
              <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
              {% else %}
                <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                <a class="nav-link" href="{% url 'users:registration' %}">Register</a>
          {% endif %}

            <a class="nav-link" href="{% url 'courses:create-course' %}">Add course</a>
            <a class="nav-link" href="{% url 'courses:create-subject' %}">Add subject</a>


      </div>
    </div>
  </div>
</nav>